### ISSUE TITLE
go generate bug

### ISSUE THREAD

**Issue by akatsuki105** [godot-go/godot-go#106]
> I'm not good at English, so I use Google Translate.
> I also know almost nothing at all about the inner workings of godot.

`godot-go` converts PascalCase to snake_case on `go generate`, shouldn't `GDExtensionInterfaceCallableCustomGetUserData` be `...userdata` instead of `...user_data`?

**References**

- https://github.com/godotengine/godot/blob/master/core/extension/gdextension_interface.h#L2395C17-L2395C62
- https://github.com/godotengine/godot/blob/4e990cd7e51d17cf24f854cc33b2715eaa27200f/core/extension/gdextension_interface.cpp#L1317C14-L1317C54

**Comment by pcting** [comment]
you're referring to this? https://github.com/godot-go/godot-go/blob/48ae418ad7b7f207ef3ab06ccd2c51f51359be19/pkg/ffi/ffi.gen.go#L320

these are all parsed from the `gdextension_interface.h` file: https://github.com/godot-go/godot-go/blob/48ae418ad7b7f207ef3ab06ccd2c51f51359be19/godot_headers/godot/gdextension_interface.h#L2395

i'll update the bindings against the latest godot snapshot to see if that changes anything

**Comment by akatsuki105** [comment]
Sorry. I was wrong, and you are indeed right.
