### ISSUE TITLE
add `yield` support

### ISSUE THREAD

**Issue by pcting** [godot-go/godot-go#16]
**Is your feature request related to a problem? Please describe.**
In the Dodge the Creep demo app, there's a function in HUD.gd:
```
func show_game_over():
	show_message("Game Over")
	yield($MessageTimer, "timeout")
	$MessageLabel.text = "Dodge the\nCreeps"
	$MessageLabel.show()
	yield(get_tree().create_timer(1), "timeout")
	$StartButton.show()
```
the equivalent in Go is found [here](https://github.com/godot-go/godot-go-demo-projects/blob/8d33009c8503104aff1ee547da9ab7e10fbd7ce0/2d/dodge_the_creeps/pkg/dtc/hud.go#L63). a helper function could make this pattern easier to construct and less prone to error. 

**Describe the solution you'd like**
it'll be nice to be able to interface with godot's signal mechanism through go channels.

**Describe alternatives you've considered**
alternatively we can go with a helper function that mimics yield

**Comment by somersbmatthews** [comment]
Could not find the word "yield" in any of the code. https://github.com/godot-go/godot-go-demo-projects/search?q=yield
Has this issue been resolved? @pcting

**Comment by pcting** [comment]
this ticket is meant to provide gdscript's `yield` support; example [here](https://github.com/godotengine/godot-demo-projects/blob/master/2d/dodge_the_creeps/HUD.gd#L13).

this is mostly for quality of life

**Comment by somersbmatthews** [comment]
oh, in the godot-engine org, not the godot-go org.

**Comment by pcting** [comment]
so just to give you perspective, this is the equivalent go code, which is not as nice: https://github.com/godot-go/godot-go-demo-projects/blob/master/2d/dodge_the_creeps/pkg/dtc/hud.go#L63

**Comment by pcting** [comment]
closing this out as i've deprecated the godot 3.x work favor of godot 4
