### ISSUE TITLE
Auto-wire up nodes on structs with field annotations 

### ISSUE THREAD

**Issue by pcting** [godot-go/godot-go#17]
**Is your feature request related to a problem? Please describe.**
we need something similar to the GDScript dollar sign operator.

**Describe the solution you'd like**
maybe something like this for ease of use:
```
type HUD struct {
	gdnative.CanvasLayerImpl
	gdnative.UserDataIdentifiableImpl

	messageLabel gdnative.Label `gdnative_child:"child_node/message_label"`
	messageTimer gdnative.Timer `gdnative_child:"message_timer"`
	startButton gdnative.Button `gdnative_child:"start_button"`
}
```
the code above will automatically initialize fields with `gdnative_child` annotations and automatically executing a find_node with the respective path saving the user from having to write boilerplate code of finding the child node.

**Comment by ekozan** [comment]
Hello @pcting 

You think about some thing like this ? 

```golang

func (o *SomeCLass) GetGDNativeObject() {

	t := reflect.ValueOf(o).Elem()

	for i := 0; i < t.NumField(); i++ {
		vf := t.Field(i)
		tf := t.Type().Field(i)
		path, ok := tf.Tag.Lookup("gdnative_child")
		if ok {

			creatorfunc := // registry or switch with tf.Type.String() for get creator func 

			if vf.IsValid() && creatorfunc != nil{
                                   
				owner := reflect.ValueOf(o.GetNode(gdnative.NewNodePath(path)).GetOwnerObject())

				object := creatorfunc(owner)

				vf.Set(reflect.ValueOf(object))
			}
		}
	}
}

```

The ony problem is for get the New****withOwner func  two way for me 

- Hardcoded by the generator 
- Make an registry ```var newTypefactory = map[string]reflect.Type{}```

**Comment by pcting** [comment]
@ekozan i haven't worked with struct annotations before, but your approach seems reasonable. a couple things i want to mention:

1. i'm also thinking we should renamed the tag from `gdnative_child` to something like `gd_node_path` to match the underlying call. i think this could save on a lot of boilerplate code. i'm open for suggestions on alternatives though.

2. how this new function will be called? we could intercept when the "_ready" or "_update" method is called [here](https://github.com/godot-go/godot-go/blob/30e6c93e551a21b2ab5d41aa8475d560f74f7981/pkg/gdnative/class_register_method.go#L101). your method can be call right before the method that was registered.

**Comment by ekozan** [comment]
Something like this ? 

```golang

--- a/pkg/gdnative/class_register_method.go
+++ b/pkg/gdnative/class_register_method.go
@@ -106,6 +106,25 @@ func go_method_func(godotObject *C.godot_object, methodData unsafe.Pointer, user
                log.Panic("method not found", StringField("method", methodName))
        }
 
+       if methodName == "Ready" {
+               log.Debug("->", StringField("Class", instValue.String()), StringField("method", methodName))
+               elem := instValue.Elem()
+               for i := 0; i < elem.NumField(); i++ {
+                       vf := elem.Field(i)
+                       tf := elem.Type().Field(i)
+                       nodepath, ok := tf.Tag.Lookup("gd_node_path")
+                       if ok {
+                               if vf.IsValid() {
+                                       owner := instValue.MethodByName("GetNode").Call([]reflect.Value{reflect.ValueOf(NewNodePath(nodepath))})[0].Interface().(Node).GetOwnerObject()
+                                       
+                                      // switch or map ? 
+
+                                       vf.Set(reflect.ValueOf(somevalue))
+                               }
+                       }
+               }
+       }
```

or i need to add it on all class for avoid reflection ?

**Comment by ekozan** [comment]
it's work,  but you need to export field ... so maybe i need to add it to all class

**Comment by pcting** [comment]
going to close this out for now. i think annotations will be a nice to have. as it stands, i think annotations will be limited to auto-wiring properties. i think having auto-wiring up through naming conventions will be better as it'll work for methods, properties, signals, etc.
