### ISSUE TITLE
Add a a repository for examples

### ISSUE THREAD

**Issue by Jacalz** [godot-go/godot-go#24]
**Is your feature request related to a problem? Please describe.**
Like stated in the README.md file, documentation is a bit sparse.

**Describe the solution you'd like**
I would prefer to have a repository like `godot-go/examples` for example that could contain examples of how to use the bindings.

**Describe alternatives you've considered**
An examples folder in this repository, but I think an external repository is simpler and allows more things to be included and organized better.

**Additional context**
It would be amazing if there could be examples of varying difficulties. A very simple example would be nice too.

**Comment by pcting** [comment]
i'll have that ready in a couple weeks; i'm in the process of translating dodge the creep atm, but i plan on pushing that up when it's ready.

**Comment by Jacalz** [comment]
@pcting Thank you :)

**Comment by pcting** [comment]
@Jacalz ask and you will receive! I pushed my changes to https://github.com/godot-go/godot-go-demo-projects/tree/master/2d/dodge_the_creeps

let me know how it goes!

cheers

**Comment by Jacalz** [comment]
Thanks @pcting. Will have a look when I get some time over :)
FYI, the README says that it’s written in gdscript, which I believe it isn’t?

**Comment by pcting** [comment]
Ya, you're right; that readme should be updated as it's copied directly from the main [godot-demo-projects](https://github.com/godotengine/godot-demo-projects/tree/master/2d/dodge_the_creeps) repository.

**Comment by pcting** [comment]
@Jacalz README.md fixed. I'm going to close this out for now, but please update me when you run the game; I'd like to know that it's working on someone else's machine!

if there are any issues that come up, please reopen this ticket.

Cheers!

**Comment by Jacalz** [comment]
It seems to work fine. Thank you for all your hard work :)

**Comment by Jacalz** [comment]
Just one last little suggestion. I think it is a bit too much to call the examples repository for `godot-go-example-projects` when `godot-go` is the organization name. It could just be `example-projects` in my opinion.
