### ISSUE TITLE
Automatic downcast wrapped structs for methods that return classes

### ISSUE THREAD

**Issue by pcting** [godot-go/godot-go#27]
**Is your feature request related to a problem? Please describe.**
Example:

```
resLoader := gdnative.GetSingletonResourceLoader()
res := resLoader.Load("res://Mob.tscn", "", false)
log.Debug("MOB PackedScene: " + res.ToString())
```
Load returns a `Resource` struct, but it can be downcasted to a `PackedScene` struct.

So the practice I've been following is performing the right after getting back the struct:
```
var scene := gdnative.NewPackedSceneWithOwner(res.GetOwnerObject())
```
The demo project has this everywhere as well: https://github.com/godot-go/godot-go-demo-projects/blob/0cdda28cec9ad2ce4d4e9980833ea946271bc63f/2d/dodge_the_creeps/pkg/dtc/hud.go#L48

**Describe the solution you'd like**
Modify the codegen to perform the downcast automatically before returning.

**Describe alternatives you've considered**
Keep things as is.

**Comment by ekozan** [comment]
We can register all New*****FromOwner func 
and make an Downcast on GetOwnerObject with something like this ? 

But the type of object are in proprety ? 

```golang
var constructorRegistry = make(map[string]reflect.Type)

func RegisterConstructor(name string,typedNil interface{}) {
    typeRegistry[name] = reflect.TypeOf(typedNil).Elem()
}

func GetConstructor(name string) interface{} {
    return reflect.New(typeRegistry[name]).Elem().Interface()
}

```

**Comment by pcting** [comment]
Yup, that was what I was thinking. That would be the easiest way to approach this problem. Reflection could probably be avoided by having a map of functions since the function signature is the same for all the constructors

```
ownerConstructors := map[string]func(*GodotObject) Class

...
ownerConstructors["Packed scene"] = NewPackedSceneFromOwnerAsClass
```

**Comment by ekozan** [comment]
i dont uderstand  ``` Class``` 

anyway my way is not possible in go because interface{} need to be cast 

an other way is to return an ```Object Struct```

```
type Godotocbject struct {
   PackedScene PackedScene
   Label         Label
   ....
}
```

but 
```var scene := res.GetOwnerObject().PackedScene``` 
or
```var scene := res.GetOwnerObject().(PackedScene)``` 

is same as ```var scene := gdnative.NewPackedSceneWithOwner(res.GetOwnerObject()) ``` for me 
 
so  it's an dead end ?

**Comment by pcting** [comment]
i haven't tried type assertions, but might be okay to do that with the current implementation since all class structs have have the same layout in memory, but it's unsafe. if we add additional fields to any of the structs, we'll probably start seeing errors.

take a look at the the `Node.GetNode` method as an example:
```
func (o NodeImpl) GetNode(path NodePath) Node {

	// Build null-terminated method arguments array
	// We cannot just use make() to create the slice because cgo
	// prohibits passing nested go pointers to C.
	ptrCArrSize := 1 + 1

	ptrArguments, ptrCArr := AllocNewSlice(ptrCArrSize)

	ptrArguments[ptrCArrSize-1] = nil

	/* USAGE_GDNATIVE_REF (NodePath / NodePath) */
	_arg0 := path
	ptrArguments[0] = unsafe.Pointer(&_arg0)

	/* USAGE_GODOT_CLASS (Node / Node) */
	var ret *GodotObject

	// Call the parent method. Node / Node
	nodeGetNodeMethodBind.Ptrcall(o.Owner, ptrArguments, unsafe.Pointer(&ret))

	defer Free(unsafe.Pointer(ptrCArr))

	runtime.KeepAlive(_arg0)

	runtime.KeepAlive(ptrArguments)

	if ret == nil {
		return nil
	}

	/* USAGE_GODOT_CLASS (Node / Node) */
	return NewNodeWithOwner(ret)

}
```

the problem is the last return statement:
```
return NewNodeWithOwner(ret)
```

lets look at the function implementation:
```
// NewNodeWithOwner wraps the GodotObject.
func NewNodeWithOwner(owner *GodotObject) Node {
	wrapped := *(*WrappedImpl)(C.go_godot_nativescript_get_instance_binding_data(Nativescript11Api, RegisterState.LanguageIndex, unsafe.Pointer(owner)))

	m := &NodeImpl{}
	m.WrappedImpl = wrapped

	if m.Owner == nil {
		log.Panic("owner should not be null")
	}

	if m.TypeTag == EmptyTypeTag {
		log.Panic("type tag should not be zero")
	}

	return m
}
```

so as the code exists, the GetNode method will return the `*GodotObject` wrapped in a `NodeImpl struct`, even though it could be wrapped in a `PackedSceneImpl` instead. I'm not 100% certain, but i think the type assertion would fail if you tried to type assert a `NodeImpl` into a `PackedScene`.

to allow the type assertion safely, we'll need to modify the `NewNodeWithOwner` function to something like the following:
```
constructor := wrappedConstructors[m.TypeTag]
return constructor(wrapped)
```

the `wrapped` variable will have the `TypeTag` of `PackedScene` and not `Node` in this case, which is great! we can take the TypeTag to look up the PackedScene constructor and use that to return the proper PackedSceneImpl.

once this happens, then your type assertion can be safely applied.

correct me if i'm wrong as this is all theoretical and untested.

**Comment by ekozan** [comment]
for win only one line of code , we will add  : 

- code complexity, 
- estetic ( for me make an assertion with normal api is bad ) 
- maybe slow execution speed 



in my mind 

```var scene := gdnative.NewPackedSceneWithOwner(res.GetOwnerObject())```
is better than ```var scene := res.GetOwnerObject().(PackedScene)```

it's just not worth it for me 

Maybe we can stall this one and work on struct tag  one who can make our life simpler

**Comment by pcting** [comment]
in the end, it'll look more like this:

```
scene := p.GetNode(gdnative.NodePath("somepath/object")).(PackedScene)
```

the end goal would be to prevent exposing `*GodotObject`. i think i can knock this one out easily once i get past the SetFinalizer / memory management ticket i'm on; it's kicking my butt.

**Comment by pcting** [comment]
closing this out as i've deprecated the godot 3.x work favor of godot 4
