### ISSUE TITLE
Crash KinematicBody2

### ISSUE THREAD

**Issue by ekozan** [godot-go/godot-go#32]
First :) 

THX FOR YOUR WORK 

I got an strange bug i try to play with KinematicBody2D

**Describe the bug**

`collision := p.MoveAndCollide(velocity) `

make an beautifull 

```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
-- END OF BACKTRACE --
```

**To Reproduce**

```golang
        animatedSprite := gdnative.NewAnimatedSpriteWithOwner(p.GetNode(gdnative.NewNodePath("AnimatedSprite")).GetOwnerObject())
	animatedSprite.Stop()
	var velocity = p.getInputs()
	v1 := velocity.Normalized()
	velocity = v1.OperatorMultiplyScalar(float32(p.speed.AsReal()))
	if velocity.Length() <= 0 {
		log.Debug("no move")
	} else {
		velocity = velocity.OperatorMultiplyScalar(float32(delta))
		str := velocity.AsString()
		log.Debug(str.AsGoString())
		collision := p.MoveAndCollide(velocity, true, true, true)

		if collision != nil {
		    log.Debug("I collided with " + collision.GetCollider().ToString())
		}
	}
```

**Expected behavior**
Player move

**Screenshots**
My Project Tree

<img width="225" alt="Capture d’écran 2020-11-06 à 19 46 12" src="https://user-images.githubusercontent.com/688184/98403109-bd53b780-2068-11eb-80cd-0b93ca01a5b6.png">

My npc Tree
<img width="225" alt="Capture d’écran 2020-11-06 à 19 39 55" src="https://user-images.githubusercontent.com/688184/98402600-dc9e1500-2067-11eb-89b7-a37e4475b559.png">

**Desktop (please complete the following information):**
 - OS: [MAC OS]
 - Architecture [amd64]
.
Any Idéa ?

**Comment by pcting** [comment]
Thanks for the interest in my project! I'll have to give this a try tonight as I can't see any obvious issues.

**Comment by ekozan** [comment]
https://github.com/ekozan/godotIA <- I uploaded my project if you need it 

if you need more info just ask  

I hope it's not an error of mine

**Comment by pcting** [comment]
it's a bug in the library; the codegen didn't include a short-circuit if the move_and_collide returns nil. it should be a simple fix

**Comment by pcting** [comment]
@ekozan godot-go 0.0.13 should have the fix. thanks for bringing up the problem! i'll close out the ticket for now, but please leave a comment or reopen the issue if the crash persists.

i left a PR here: https://github.com/ekozan/godotIA/pull/1 that has the fix

**Comment by ekozan** [comment]
@pcting  it works thx  👍
