### ISSUE TITLE
Clean up type and class codegen

### ISSUE THREAD

**Issue by pcting** [godot-go/godot-go#38]
**Is your feature request related to a problem? Please describe.**
The codegen for types and classes are a mangled mess due to the iterative process and evolving changes of how the code is generated.

**Describe the solution you'd like**
Refactor the code to utilize an AST in an attempt to clean up the code. Maybe https://golang.org/pkg/go/ast/

**Describe alternatives you've considered**
At first I was thinking about going with ANTLR. This fits for the use case of parsing the gdnative C header into Go; however, there's still the parsing of XML into Go. Maybe ANTLR can still work for type generation.

**Comment by ekozan** [comment]
why we need to parse C  header ??

**Comment by pcting** [comment]
the C headers parsing provides 2 things:

1. cgo doesn't support calling function pointers; you have to add wrapper code to call the function pointers from C; you can check out any of the *.gen.c and *.gen.h files in the project as an example.
2. we need to generate codegen to make interacting with godot data type primatives such as Vector2 more golang-like. without the code gen, we'd effectively need to call C code directly; this is what the [types.gen.go](https://github.com/godot-go/godot-go/blob/master/pkg/gdnative/types.gen.go) file contains.

Hope this helps; I think once the major issues are complete, I'll write an article explaining all the aspects of the project

**Comment by pcting** [comment]
closing this out as i've deprecated the godot 3.x work favor of godot 4
