### ISSUE TITLE
Hi, is this project still being maintained? Does it support godot 3.4?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [godot-go/godot-go#42]

**Comment by Splizard** [comment]
Not sure if this project will be updated but I'm currently working on https://github.com/readykit/gd which is a set of Godot 4.0 bindings for Go 1.9, it won't be supporting Godot 3.x but the project may be of interest to those who are looking for an updated set of bindings.

**Comment by Yakumo-Yukari** [comment]
> Not sure if this project will be updated but I'm currently working on https://github.com/readykit/gd which is a set of Godot 4.0 bindings for Go 1.9, it won't be supporting Godot 3.x but the project may be of interest to those who are looking for an updated set of bindings.

Thank you, I am very interested in this project that you have recommended

**Comment by pcting** [comment]
I just recently uploaded my godot 4 / GDExtension initial code changes. please take a look when you get the chance.

I left a small message in the discussion board: https://github.com/godot-go/godot-go/discussions/43
