### ISSUE TITLE
Network server 

### ISSUE THREAD

**Issue by gedw99** [godot-go/godot-go#74]
Would be cool to build a basic golang backend Server to act as a game server that works with godot.

according to the v4 docs it can use webrtc or websockets, both of which golang supports.

a nats based broker is used often as a game server because of it pub sub m, request / response and queue groups. 

Nats can automatically do web sockets, so seems like a great fit.

wbrtc with pion can also be done using Livekit which is golang too. Under the hood Livekit uses nats.

I don’t know what auth mechanisms godot supports but nats supports jwt, tokens …

**Comment by pcting** [comment]
going to close this out and marking it as out of scope
